/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6SMMY9YQqNc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function addProduct() {
  const [product, setProduct] = useState({
    image: "/placeholder.svg",
    name: "Cozy Knit Sweater",
    description: "A soft and warm knit sweater perfect for chilly days.",
    price: 59.99,
  })
  const handleSubmit = (e) => {
    e.preventDefault()
    setProduct({
      image: "/placeholder.svg",
      name: "Cozy Knit Sweater",
      description: "A soft and warm knit sweater perfect for chilly days.",
      price: 59.99,
    })
  }
  return (
    <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto px-4 py-12">
      <div className="grid gap-4">
        <img
          src="/placeholder.svg"
          alt={product.name}
          width={600}
          height={600}
          className="w-full rounded-lg object-cover aspect-square"
        />
      </div>
      <div className="grid gap-6">
        <form onSubmit={handleSubmit}>
          <div className="grid gap-2">
            <Label htmlFor="description">Product Description</Label>
            <Textarea id="description" placeholder="Enter product description" className="w-full" />
          </div>
          <div className="grid gap-2">
            <Label htmlFor="price">Price</Label>
            <Input type="number" id="price" placeholder="Enter product price" className="w-full" />
          </div>
          <Button type="submit" className="mt-4">
            Create Ecommerce Website
          </Button>
        </form>
      </div>
    </div>
  )
}
