/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/6SMMY9YQqNc
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Label } from "@/components/ui/label"
import { Textarea } from "@/components/ui/textarea"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function addProduct() {
  const [product, setProduct] = useState({
    image: "/placeholder.svg",
    name: "Cozy Knit Sweater",
    description: "A soft and warm knit sweater perfect for chilly days.",
    price: 59.99,
  })
  const [files, setFiles] = useState([])
  const handleFileUpload = (event: React.ChangeEvent<HTMLInputElement>) => {
    if (event.target.files) {
      setFiles(event.target.files);
    }
  };
  
  const handleSubmit = (e) => {
    e.preventDefault()
    setProduct({
      image: "/placeholder.svg",
      name: "Cozy Knit Sweater",
      description: "A soft and warm knit sweater perfect for chilly days.",
      price: 59.99,
    })
  }
  return (
    <div className="grid md:grid-cols-2 gap-8 max-w-6xl mx-auto px-4 py-12">
      <div className="grid gap-4">
        <img
          src="/placeholder.svg"
          alt={product.name}
          width={600}
          height={600}
          className="w-full rounded-lg object-cover aspect-square"
        />
        <div className="flex items-center gap-2">
          <Button variant="outline" size="sm">
            <UploadIcon className="w-4 h-4 mr-2" />
            Add files
          </Button>
          <input type="file" multiple className="hidden" onChange={handleFileUpload} />
        </div>
      </div>
      <div className="grid gap-6 my-2">
        <form onSubmit={handleSubmit}>
          <div className="grid gap-2 my-4">
            <Label htmlFor="description">Product Description</Label>
            <Textarea id="description" placeholder="Enter product description" className="w-full" />
          </div>
          <div className="grid gap-2 my-4">
            <Label htmlFor="price">Name</Label>
            <Input type="string" id="name" placeholder="Enter product name" className="w-full" />
          </div>
          <div className="grid gap-2 my-4">
            <Label htmlFor="price">Price</Label>
            <Input type="number" id="price" placeholder="Enter product price" className="w-full" />
          </div>
          <Button type="submit" className="mt-4">
            Create Ecommerce Website
          </Button>
        </form>
      </div>
    </div>
  )
}

export default addProduct;

function UploadIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
      <polyline points="17 8 12 3 7 8" />
      <line x1="12" x2="12" y1="3" y2="15" />
    </svg>
  )
}