/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/jyWe6afNdtC
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Arimo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { deflate } from "zlib"

export function Component() {
  return (
    <div className="flex flex-col min-h-screen">
      <header className="bg-primary text-primary-foreground py-4 px-6 md:px-8 lg:px-12">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" className="text-2xl font-bold" prefetch={false}>
            Acme Marketplace
          </Link>
          <div className="relative w-full max-w-md">
            <Input
              type="search"
              placeholder="Search for products..."
              className="w-full rounded-full bg-primary-foreground/10 px-4 py-2 pr-10 focus:outline-none focus:ring-2 focus:ring-primary"
            />
            <SearchIcon className="absolute right-3 top-1/2 -translate-y-1/2 w-5 h-5 text-primary-foreground/50" />
          </div>
          <div className="flex items-center gap-4">
            <Link href="#" className="hover:text-primary-foreground/80" prefetch={false}>
              <UserIcon className="w-6 h-6" />
              <span className="sr-only">Account</span>
            </Link>
          </div>
        </div>
      </header>
      <main className="flex-1">
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-6 md:px-8 lg:px-12">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Popular Products</h2>
              <Link href="#" className="text-primary hover:text-primary-foreground/80" prefetch={false}>
                See all
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-8 lg:gap-10">
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="/product" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 1"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 1</h3>
                    <p className="text-muted-foreground">$19.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  10 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 2"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 2</h3>
                    <p className="text-muted-foreground">$29.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  25 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 3"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 3</h3>
                    <p className="text-muted-foreground">$39.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  8 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 4"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 4</h3>
                    <p className="text-muted-foreground">$49.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  18 in stock
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-12 md:py-16 lg:py-20">
          <div className="container mx-auto px-6 md:px-8 lg:px-12">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl md:text-3xl lg:text-4xl font-bold">Recently Purchased</h2>
              <Link href="#" className="text-primary hover:text-primary-foreground/80" prefetch={false}>
                See all
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-6 md:gap-8 lg:gap-10">
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 5"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 5</h3>
                    <p className="text-muted-foreground">$59.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  6 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 6"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 6</h3>
                    <p className="text-muted-foreground">$69.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  12 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 7"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 7</h3>
                    <p className="text-muted-foreground">$79.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  4 in stock
                </div>
              </div>
              <div className="bg-background rounded-lg overflow-hidden shadow-lg relative">
                <Link href="#" prefetch={false}>
                  <div className="aspect-square">
                    <img
                      src="/placeholder.svg"
                      alt="Product 8"
                      width={400}
                      height={400}
                      className="w-full h-full object-cover"
                      style={{ aspectRatio: "400/400", objectFit: "cover" }}
                    />
                  </div>
                  <div className="p-4">
                    <h3 className="text-lg font-medium">Product 8</h3>
                    <p className="text-muted-foreground">$89.99</p>
                  </div>
                </Link>
                <div className="absolute bottom-4 right-4 bg-muted/80 text-muted-foreground px-2 py-1 rounded-md text-xs">
                  9 in stock
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-muted text-muted-foreground py-6 md:py-8 lg:py-10">
        <div className="container mx-auto px-6 md:px-8 lg:px-12 flex flex-col md:flex-row items-center justify-between">
          <p className="text-sm">&copy; 2024 Acme Marketplace. All rights reserved.</p>
          <nav className="flex items-center gap-4 md:gap-6 lg:gap-8 mt-4 md:mt-0">
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              About
            </Link>
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              Contact
            </Link>
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              Privacy
            </Link>
            <Link href="#" className="hover:text-muted-foreground/80" prefetch={false}>
              Terms
            </Link>
          </nav>
        </div>
      </footer>
    </div>
  )
}

export default Component;

function DollarSignIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <line x1="12" x2="12" y1="2" y2="22" />
      <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
    </svg>
  )
}


function PlusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  )
}


function SearchIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="11" cy="11" r="8" />
      <path d="m21 21-4.3-4.3" />
    </svg>
  )
}


function UserIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
      <circle cx="12" cy="7" r="4" />
    </svg>
  )
}
