/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/wkvuIV58HaD
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Rubik } from 'next/font/google'
import { IBM_Plex_Sans } from 'next/font/google'

rubik({
  subsets: ['latin'],
  display: 'swap',
})

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { Card, CardHeader, CardTitle, CardDescription, CardContent, CardFooter } from "@/components/ui/card"
import { Button } from "@/components/ui/button"

export function orderSummary() {
  return (
    <div className="flex min-h-screen w-full flex-col bg-background">
      <header className="bg-primary text-primary-foreground py-4 px-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="#" prefetch={false}>
            <LogInIcon className="h-6 w-auto" />
          </Link>
          <nav className="flex items-center gap-4">
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Checkout
            </Link>
            <Link href="#" className="font-medium hover:underline" prefetch={false}>
              Account
            </Link>
          </nav>
        </div>
      </header>
      <main className="container mx-auto flex flex-1 flex-col items-center justify-center gap-8 px-4 py-8 sm:px-6 lg:px-8">
        <Card className="w-full max-w-md">
          <CardHeader>
            <CardTitle>Order Summary</CardTitle>
            <CardDescription>Review your order details before proceeding.</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid gap-2">
                <div className="flex items-center justify-between">
                  <div>
                    <div className="font-medium">Item 1</div>
                    <div className="text-muted-foreground">Description of Item 1</div>
                  </div>
                  <div className="flex items-center gap-2">
                    <img
                      src="/placeholder.svg"
                      alt="Order QR Code"
                      width={32}
                      height={32}
                      className="rounded-md"
                      style={{ aspectRatio: "32/32", objectFit: "cover" }}
                    />
                    <div>Quantity: 2</div>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <div>Price</div>
                  <div>$50</div>
                </div>
              </div>
              <div className="flex items-center justify-between">
                <div>Order Code</div>
                <div>OC12345678</div>
              </div>
            </div>
          </CardContent>
          <CardFooter>
            <Button
              type="submit"
              className="w-full"
              onClick={() => {
                const transactionDetails = {
                  amount: "$114.99",
                  paymentMethod: "Telebirr",
                }
                window.location.href = `/payment-verification?${new URLSearchParams(transactionDetails).toString()}`
              }}
            >
              Verify Order
            </Button>
          </CardFooter>
        </Card>
      </main>
    </div>
  )
}

function LogInIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M15 3h4a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2h-4" />
      <polyline points="10 17 15 12 10 7" />
      <line x1="15" x2="3" y1="12" y2="12" />
    </svg>
  )
}
