/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/iHYKStb2upy
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Baskerville } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_baskerville({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card"

export function productTemp() {
  return (
    <div className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-8 max-w-6xl mx-auto py-8 px-4 md:px-0">
      <div className="grid gap-8">
        <div className="grid grid-cols-1 md:grid-cols-[400px_1fr] gap-8">
          <img
            src="/placeholder.svg"
            alt="Product Image"
            width={400}
            height={400}
            className="w-full aspect-square object-cover rounded-lg"
          />
          <div className="grid gap-4">
            <h1 className="text-2xl md:text-3xl font-bold">Vintage Leather Briefcase</h1>
            <div className="flex items-center gap-2">
              <span className="text-3xl font-bold">$149.99</span>
              <Badge variant="secondary">Free Shipping</Badge>
            </div>
            <Button size="lg" className="w-full">
              Buy It Now
            </Button>
          </div>
        </div>
        <div className="grid gap-4">
          <h2 className="text-xl font-bold">Product Details</h2>
          <div className="grid gap-2">
            <p>
              This vintage leather briefcase is a timeless classic that combines style and functionality. Crafted from
              high-quality full-grain leather, it features a spacious main compartment, multiple pockets, and a durable
              shoulder strap for easy carrying.
            </p>
            <div className="grid sm:grid-cols-2 gap-4">
              <div className="grid gap-1">
                <span className="font-medium">Dimensions:</span>
                <span>16" x 12" x 4"</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Weight:</span>
                <span>3.5 lbs</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Material:</span>
                <span>Full-grain Leather</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Closure:</span>
                <span>Zipper</span>
              </div>
            </div>
          </div>
          <div className="grid gap-2">
            <h3 className="text-lg font-bold">Key Features:</h3>
            <ul className="grid gap-2">
              <li className="flex items-center gap-2">
                <CheckIcon className="w-5 h-5 text-primary" />
                Durable full-grain leather construction
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="w-5 h-5 text-primary" />
                Spacious main compartment with multiple pockets
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="w-5 h-5 text-primary" />
                Adjustable and removable shoulder strap
              </li>
              <li className="flex items-center gap-2">
                <CheckIcon className="w-5 h-5 text-primary" />
                Stylish and professional design
              </li>
            </ul>
          </div>
        </div>
      </div>
      <div className="grid gap-8">
        <Card>
          <CardHeader>
            <CardTitle>Seller Information</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Seller Avatar"
                  width={40}
                  height={40}
                  className="rounded-full"
                  style={{ aspectRatio: "40/40", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">Vintage Goods</h4>
                  <p className="text-sm text-muted-foreground">Top-rated seller</p>
                </div>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Location:</span>
                <span>New York, NY</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Feedback:</span>
                <div className="flex items-center gap-2">
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-primary" />
                  <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  <span className="text-sm">4.9 (1,234 reviews)</span>
                </div>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Shipping Details</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="grid gap-1">
                <span className="font-medium">Shipping Method:</span>
                <span>Standard Shipping</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Estimated Delivery:</span>
                <span>5-7 business days</span>
              </div>
              <div className="grid gap-1">
                <span className="font-medium">Returns:</span>
                <span>30-day returns</span>
              </div>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardHeader>
            <CardTitle>Customer Reviews</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="grid gap-4">
              <div className="flex items-center gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Reviewer Avatar"
                  width={40}
                  height={40}
                  className="rounded-full"
                  style={{ aspectRatio: "40/40", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">John Doe</h4>
                  <div className="flex items-center gap-2">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-muted stroke-muted-foreground" />
                  </div>
                </div>
              </div>
              <p>
                "This briefcase is absolutely amazing! The quality is\n outstanding, and it looks so stylish. I've been
                using it for\n work and it's been a game-changer. Highly recommend!"
              </p>
              <div className="flex items-center gap-2">
                <img
                  src="/placeholder.svg"
                  alt="Reviewer Avatar"
                  width={40}
                  height={40}
                  className="rounded-full"
                  style={{ aspectRatio: "40/40", objectFit: "cover" }}
                />
                <div>
                  <h4 className="font-medium">Jane Smith</h4>
                  <div className="flex items-center gap-2">
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                    <StarIcon className="w-5 h-5 fill-primary" />
                  </div>
                </div>
              </div>
              <p>
                "I'm absolutely in love with this briefcase! The craftsmanship\n is top-notch, and it's the perfect size
                for my daily\n commute. I couldn't be happier with my purchase."
              </p>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}


function StarIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26 12 2" />
    </svg>
  )
}
